name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-boost
            mingw-w64-x86_64-mpg123
            vim
      - name: Checkout ProjectorRays
        uses: actions/checkout@v3
      - name: Build
        run: |
          mingw32-make
